// ui/src/components/LogConsole.tsx
import React, { useEffect, useRef, useState } from 'react';
import { ChevronUp, ChevronDown, Copy, Trash2, Download } from 'lucide-react';

export interface LogEntry {
  timestamp: Date;
  level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';
  message: string;
  source?: string;
}

interface LogConsoleProps {
  logs: LogEntry[];
  onClear?: () => void;
  maxHeight?: string;
}

export const LogConsole: React.FC<LogConsoleProps> = ({ 
  logs, 
  onClear,
  maxHeight = '300px' 
}) => {
  const [isExpanded, setIsExpanded] = useState(true);
  const [filter, setFilter] = useState<'ALL' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'>('ALL');
  const [autoScroll, setAutoScroll] = useState(true);
  const consoleRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (autoScroll && consoleRef.current) {
      consoleRef.current.scrollTop = consoleRef.current.scrollHeight;
    }
  }, [logs, autoScroll]);

  const filteredLogs = logs.filter(log => 
    filter === 'ALL' || log.level === filter
  );

  const getLevelColor = (level: LogEntry['level']) => {
    switch (level) {
      case 'DEBUG': return 'text-gray-400';
      case 'INFO': return 'text-blue-400';
      case 'WARN': return 'text-yellow-400';
      case 'ERROR': return 'text-red-400';
    }
  };

  const formatTimestamp = (date: Date) => {
    return date.toLocaleTimeString('en-US', { 
      hour12: false,
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      fractionalSecondDigits: 3
    });
  };

  const copyLogs = () => {
    const text = filteredLogs
      .map(log => `[${formatTimestamp(log.timestamp)}] [${log.level}] ${log.source ? `[${log.source}] ` : ''}${log.message}`)
      .join('\n');
    navigator.clipboard.writeText(text);
  };

  const downloadLogs = () => {
    const text = logs
      .map(log => `[${formatTimestamp(log.timestamp)}] [${log.level}] ${log.source ? `[${log.source}] ` : ''}${log.message}`)
      .join('\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `moses-logs-${new Date().toISOString()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-900 border border-gray-700 rounded-lg overflow-hidden">
      {/* Header */}
      <div className="bg-gray-800 px-4 py-2 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="text-gray-400 hover:text-white transition-colors"
          >
            {isExpanded ? <ChevronDown size={20} /> : <ChevronUp size={20} />}
          </button>
          <span className="text-sm font-mono text-gray-300">
            Console Output ({filteredLogs.length} logs)
          </span>
        </div>

        <div className="flex items-center gap-2">
          {/* Filter buttons */}
          <div className="flex gap-1 mr-4">
            {(['ALL', 'DEBUG', 'INFO', 'WARN', 'ERROR'] as const).map(level => (
              <button
                key={level}
                onClick={() => setFilter(level)}
                className={`px-2 py-1 text-xs font-mono rounded transition-colors ${
                  filter === level 
                    ? 'bg-gray-700 text-white' 
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                {level}
              </button>
            ))}
          </div>

          {/* Auto-scroll toggle */}
          <label className="flex items-center gap-1 text-xs text-gray-400">
            <input
              type="checkbox"
              checked={autoScroll}
              onChange={(e) => setAutoScroll(e.target.checked)}
              className="rounded border-gray-600"
            />
            Auto-scroll
          </label>

          {/* Action buttons */}
          <button
            onClick={copyLogs}
            className="p-1 text-gray-400 hover:text-white transition-colors"
            title="Copy logs"
          >
            <Copy size={16} />
          </button>
          <button
            onClick={downloadLogs}
            className="p-1 text-gray-400 hover:text-white transition-colors"
            title="Download all logs"
          >
            <Download size={16} />
          </button>
          {onClear && (
            <button
              onClick={onClear}
              className="p-1 text-gray-400 hover:text-red-400 transition-colors"
              title="Clear logs"
            >
              <Trash2 size={16} />
            </button>
          )}
        </div>
      </div>

      {/* Console */}
      {isExpanded && (
        <div
          ref={consoleRef}
          className="bg-black p-2 overflow-y-auto font-mono text-xs"
          style={{ maxHeight }}
          onScroll={() => {
            if (consoleRef.current) {
              const { scrollTop, scrollHeight, clientHeight } = consoleRef.current;
              // Disable auto-scroll if user scrolls up
              if (scrollTop < scrollHeight - clientHeight - 10) {
                setAutoScroll(false);
              }
            }
          }}
        >
          {filteredLogs.length === 0 ? (
            <div className="text-gray-600 italic">No logs to display</div>
          ) : (
            filteredLogs.map((log, index) => (
              <div key={index} className="py-0.5 hover:bg-gray-900">
                <span className="text-gray-600">[{formatTimestamp(log.timestamp)}]</span>
                {' '}
                <span className={`${getLevelColor(log.level)} font-semibold`}>
                  [{log.level}]
                </span>
                {log.source && (
                  <>
                    {' '}
                    <span className="text-purple-400">[{log.source}]</span>
                  </>
                )}
                {' '}
                <span className="text-gray-300 whitespace-pre-wrap">{log.message}</span>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
};

// ui/src/components/LogConsole.vue
<template>
  <div class="log-console" :class="{ collapsed: !isExpanded }">
    <!-- Header -->
    <div class="console-header">
      <div class="header-left">
        <button @click="toggleExpanded" class="toggle-btn">
          <span>{{ isExpanded ? '▼' : '▶' }}</span>
        </button>
        <span class="console-title">Console Output ({{ filteredLogs.length }} logs)</span>
      </div>

      <div class="header-right">
        <!-- Filter buttons -->
        <div class="filter-buttons">
          <button 
            v-for="level in ['ALL', 'DEBUG', 'INFO', 'WARN', 'ERROR']"
            :key="level"
            @click="filter = level"
            :class="{ active: filter === level }"
            class="filter-btn"
          >
            {{ level }}
          </button>
        </div>

        <!-- Auto-scroll toggle -->
        <label class="auto-scroll">
          <input 
            type="checkbox" 
            v-model="autoScroll"
            @change="handleAutoScrollChange"
          />
          Auto-scroll
        </label>

        <!-- Action buttons -->
        <button @click="copyLogs" class="action-btn" title="Copy logs">
          📋
        </button>
        <button @click="downloadLogs" class="action-btn" title="Download logs">
          💾
        </button>
        <button @click="clearLogs" class="action-btn clear" title="Clear logs">
          🗑️
        </button>
      </div>
    </div>

    <!-- Console Output -->
    <div 
      v-if="isExpanded"
      ref="consoleOutput"
      class="console-output"
      @scroll="handleScroll"
      @keydown.ctrl.a.prevent="selectAll"
      @keydown.ctrl.c="copySelection"
      tabindex="0"
    >
      <div v-if="filteredLogs.length === 0" class="no-logs">
        No logs to display
      </div>
      <div 
        v-else
        v-for="(log, index) in filteredLogs" 
        :key="index"
        class="log-entry"
        @contextmenu.prevent="copyLogEntry(log)"
        :title="'Right-click to copy this log entry'"
      >
        <span class="timestamp">[{{ formatTimestamp(log.timestamp) }}]</span>
        <span :class="['level', log.level.toLowerCase()]">[{{ log.level }}]</span>
        <span v-if="log.source" class="source">[{{ log.source }}]</span>
        <span class="message">{{ log.message }}</span>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'LogConsole',
  props: {
    maxHeight: {
      type: String,
      default: '300px'
    }
  },
  data() {
    return {
      logs: [],
      isExpanded: true,
      filter: 'ALL',
      autoScroll: true
    };
  },
  computed: {
    filteredLogs() {
      if (this.filter === 'ALL') {
        return this.logs;
      }
      return this.logs.filter(log => log.level === this.filter);
    }
  },
  methods: {
    addLog(level, message, source = null) {
      const entry = {
        timestamp: new Date(),
        level,
        message,
        source
      };
      
      this.logs.push(entry);
      
      // Keep only last 5000 logs
      if (this.logs.length > 5000) {
        this.logs = this.logs.slice(-5000);
      }
      
      // Auto-scroll if enabled
      if (this.autoScroll) {
        this.$nextTick(() => {
          this.scrollToBottom();
        });
      }
    },
    
    debug(message, source) {
      this.addLog('DEBUG', message, source);
    },
    
    info(message, source) {
      this.addLog('INFO', message, source);
    },
    
    warn(message, source) {
      this.addLog('WARN', message, source);
    },
    
    error(message, source) {
      this.addLog('ERROR', message, source);
    },
    
    toggleExpanded() {
      this.isExpanded = !this.isExpanded;
    },
    
    formatTimestamp(date) {
      const pad = (n) => n.toString().padStart(2, '0');
      const hours = pad(date.getHours());
      const minutes = pad(date.getMinutes());
      const seconds = pad(date.getSeconds());
      const ms = date.getMilliseconds().toString().padStart(3, '0');
      return `${hours}:${minutes}:${seconds}.${ms}`;
    },
    
    handleScroll() {
      if (!this.$refs.consoleOutput) return;
      
      const { scrollTop, scrollHeight, clientHeight } = this.$refs.consoleOutput;
      // Disable auto-scroll if user scrolls up
      if (scrollTop < scrollHeight - clientHeight - 10) {
        this.autoScroll = false;
      }
    },
    
    handleAutoScrollChange() {
      if (this.autoScroll) {
        this.scrollToBottom();
      }
    },
    
    scrollToBottom() {
      if (this.$refs.consoleOutput) {
        this.$refs.consoleOutput.scrollTop = this.$refs.consoleOutput.scrollHeight;
      }
    },
    
    copyLogs() {
      const text = this.filteredLogs
        .map(log => `[${this.formatTimestamp(log.timestamp)}] [${log.level}] ${log.source ? `[${log.source}] ` : ''}${log.message}`)
        .join('\n');
      
      navigator.clipboard.writeText(text).then(() => {
        this.info('Logs copied to clipboard', 'Console');
      });
    },
    
    copyLogEntry(log) {
      const text = `[${this.formatTimestamp(log.timestamp)}] [${log.level}] ${log.source ? `[${log.source}] ` : ''}${log.message}`;
      navigator.clipboard.writeText(text).then(() => {
        // Show brief feedback
        this.info('Log entry copied', 'Console');
      });
    },
    
    downloadLogs() {
      const text = this.logs
        .map(log => `[${this.formatTimestamp(log.timestamp)}] [${log.level}] ${log.source ? `[${log.source}] ` : ''}${log.message}`)
        .join('\n');
      
      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `moses-logs-${new Date().toISOString().replace(/[:.]/g, '-')}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      
      this.info('Logs downloaded', 'Console');
    },
    
    clearLogs() {
      this.logs = [];
      this.info('Console cleared', 'Console');
    },
    
    selectAll() {
      // Select all text in the console
      if (this.$refs.consoleOutput) {
        const selection = window.getSelection();
        const range = document.createRange();
        range.selectNodeContents(this.$refs.consoleOutput);
        selection.removeAllRanges();
        selection.addRange(range);
      }
    },
    
    copySelection() {
      // Let the browser handle the copy if there's selected text
      const selection = window.getSelection();
      if (selection.toString()) {
        // Browser will handle Ctrl+C naturally
        return;
      }
      // If nothing selected, copy all logs
      this.copyLogs();
    }
  }
};
</script>

<style scoped>
.log-console {
  background: #1a1a1a;
  border: 1px solid #333;
  border-radius: 4px;
  overflow: hidden;
  font-family: 'Consolas', 'Monaco', monospace;
  margin-top: 10px;
}

.console-header {
  background: #2a2a2a;
  padding: 8px 12px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #333;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 10px;
}

.toggle-btn {
  background: none;
  border: none;
  color: #888;
  cursor: pointer;
  padding: 0;
  font-size: 12px;
}

.toggle-btn:hover {
  color: #fff;
}

.console-title {
  color: #ccc;
  font-size: 13px;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 12px;
}

.filter-buttons {
  display: flex;
  gap: 4px;
}

.filter-btn {
  background: transparent;
  border: 1px solid #444;
  color: #888;
  padding: 2px 8px;
  font-size: 11px;
  cursor: pointer;
  border-radius: 3px;
  transition: all 0.2s;
}

.filter-btn:hover {
  color: #fff;
  border-color: #666;
}

.filter-btn.active {
  background: #0066cc;
  color: #fff;
  border-color: #0066cc;
}

.auto-scroll {
  display: flex;
  align-items: center;
  gap: 4px;
  color: #888;
  font-size: 12px;
}

.auto-scroll input {
  cursor: pointer;
}

.action-btn {
  background: none;
  border: none;
  color: #888;
  cursor: pointer;
  padding: 4px;
  font-size: 14px;
  transition: all 0.2s;
}

.action-btn:hover {
  color: #fff;
}

.action-btn.clear:hover {
  color: #ff4444;
}

.console-output {
  background: #0a0a0a;
  color: #d4d4d4;
  padding: 8px;
  max-height: 300px;
  overflow-y: auto;
  font-size: 12px;
  line-height: 1.4;
  user-select: text;  /* Allow text selection */
  cursor: text;       /* Show text cursor */
}

.no-logs {
  color: #666;
  font-style: italic;
  padding: 20px;
  text-align: center;
}

.log-entry {
  padding: 2px 4px;
  white-space: pre-wrap;
  word-break: break-all;
  user-select: text;  /* Ensure entries are selectable */
  position: relative;
}

.log-entry:hover {
  background: #1a1a1a;
}

/* Highlight selected text for better visibility */
.console-output ::selection {
  background: #3a6ea5;
  color: #ffffff;
}

.console-output ::-moz-selection {
  background: #3a6ea5;
  color: #ffffff;
}

.timestamp {
  color: #666;
}

.level {
  font-weight: bold;
  margin-left: 4px;
}

.level.debug {
  color: #888;
}

.level.info {
  color: #4a9eff;
}

.level.warn {
  color: #ffb84d;
}

.level.error {
  color: #ff5555;
}

.source {
  color: #b19cd9;
  margin-left: 4px;
}

.message {
  margin-left: 4px;
}

/* Dark scrollbar */
.console-output::-webkit-scrollbar {
  width: 8px;
}

.console-output::-webkit-scrollbar-track {
  background: #1a1a1a;
}

.console-output::-webkit-scrollbar-thumb {
  background: #444;
  border-radius: 4px;
}

.console-output::-webkit-scrollbar-thumb:hover {
  background: #555;
}

/* Collapsed state */
.log-console.collapsed .console-output {
  display: none;
}
</style>
